In [1]:
lst = []
n = int(input("Enter a number: "))

for i in range(1,n+1):
  lst.append(i)
  
print(lst)

ValueError: invalid literal for int() with base 10: ''

In [ ]:
lst # already defined in the previous cell, so no need to redefine it here

def list_element(lst):
  first_element = lst[0]
  middle_element = lst[len(lst) //2]
  lst_element = lst[-1]
  return first_element, middle_element, lst_element

print('Actual list',lst)
list_element(lst)

Actual list [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


(1, 11, 20)

In [ ]:
lst[:5]
lst[-5:]
lst[5:16]

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

In [ ]:
square_list = list(map(lambda x: x**2, lst[:10]))
square_list



[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [ ]:
even_numbers = list(filter(lambda x: x % 2 == 0, lst))
even_numbers
import numpy as np
np.count_nonzero(np.array(even_numbers) % 2 == 0)
even_numbers

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr.shape


(3, 3)

In [12]:
import random

random_numbers = [random.randint(1,20) for i in range(15)]
sort_ascending = print(f'sorted number in ascending order is{sorted(random_numbers)}')
sort_descending = print(f'sorted number in descending order is',sorted(random_numbers, reverse=True))
unique_numbers = set(random_numbers)
print(f'unique numbers are {unique_numbers}')

sorted number in ascending order is[1, 2, 2, 6, 6, 9, 10, 11, 13, 13, 14, 16, 19, 19, 20]
sorted number in descending order is [20, 19, 19, 16, 14, 13, 13, 11, 10, 9, 6, 6, 2, 2, 1]
unique numbers are {1, 2, 6, 9, 10, 11, 13, 14, 16, 19, 20}


In [20]:
list_of_dict = [
  {'name': 'Alice','age':25,'city':'New York','Salary': 50000},
  {'name': 'Bob','age':30,'city':'Los Angeles','Salary': 60000},
  {'name': 'Charlie','age':35,'city':'Chicago','Salary': 70000},
  {'name': 'David','age':40,'city':'Houston','Salary': 80000},
  {'name': 'Eve','age':45,'city':'Phoenix','Salary': 90000}
]

sorted_list_of_dict = sorted(list_of_dict, key = lambda x: x['Salary'],reverse=True)
for item in sorted_list_of_dict:
  print(item)

{'name': 'Eve', 'age': 45, 'city': 'Phoenix', 'Salary': 90000}
{'name': 'David', 'age': 40, 'city': 'Houston', 'Salary': 80000}
{'name': 'Charlie', 'age': 35, 'city': 'Chicago', 'Salary': 70000}
{'name': 'Bob', 'age': 30, 'city': 'Los Angeles', 'Salary': 60000}
{'name': 'Alice', 'age': 25, 'city': 'New York', 'Salary': 50000}


In [27]:

matrix = np.array(np.arange(1, 10)).reshape(3,3)

for row in matrix:
    print(row)
  
print(f'Second row, third column element is :... {matrix[1][2]}')

[1 2 3]
[4 5 6]
[7 8 9]
Second row, third column element is :... 6


In [36]:
# Transpose of the matrix
def transpose_matrix(matrix):
  transpose = [[matrix[j][i] for j in range(len(matrix))] for i in range (len(matrix[0])) ]
  return transpose

transposed_mat = transpose_matrix(matrix)
print('Original matrix:\n', matrix)
print('Transposed matrix:\n', transposed_mat)
for transposed_row in transposed_mat:
    print(transposed_row)

Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed matrix:
 [[np.int64(1), np.int64(4), np.int64(7)], [np.int64(2), np.int64(5), np.int64(8)], [np.int64(3), np.int64(6), np.int64(9)]]
[np.int64(1), np.int64(4), np.int64(7)]
[np.int64(2), np.int64(5), np.int64(8)]
[np.int64(3), np.int64(6), np.int64(9)]


In [ ]:
def flatten_list(nested_list):
  flat_list = [item for sublist in nested_list for item in sublist]
  return flat_list

nested_list = [[1, 2, 3], [4, 5], [6, 7, 8, 9]]
flattened_list = flatten_list(nested_list)
print('Nested list:', nested_list)

print('Flattened list:', flattened_list)



Nested list: [[1, 2, 3], [4, 5], [6, 7, 8, 9]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8, 9]


(9,)

In [51]:
lst = list(range(1,11))
print(f'Original list: {lst}')

del lst[2]
del lst[4]
del lst[6]

print(f'Modified list: {lst}')

''' remember that when we are using the del command, 
we permanently delete the element from the list, 
so the index of the element will be changed after deletion. 
So we need to adjust the index accordingly.
'''

lst.insert(6,99)
lst

Original list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Modified list: [1, 2, 4, 5, 7, 8, 10]


[1, 2, 4, 5, 7, 8, 99, 10]

In [6]:
l1 = [1,2,3,4,5]
l2 = [9,8,7,6,5]

combine_list = list(zip(l1,l2))
list(combine_list)

[(1, 9), (2, 8), (3, 7), (4, 6), (5, 5)]

In [13]:
def reverse_list(lst)->list:
  return lst[::-1]

print(f'reversed list {reverse_list(l1)}')
print(f'original list {l1}')

reversed list [5, 4, 3, 2, 1]
original list [1, 2, 3, 4, 5]


In [17]:
def rotate_list(lst, n):
  n = n % len(lst)  # Handle cases where n is greater than the list length
  return lst[-n:] + lst[:-n]

print(f'rotated list {rotate_list(l1, 3)}')

rotated list [3, 4, 5, 1, 2]


In [19]:
def list_intersection(lst1,lst2):
  return lst1 & lst2

print(f'Intersection of l1 and l2 is {list_intersection(set(l1),set(l2))}')
print(f'original list l1 is {l1}')
print(f'original list l2 is {l2}')

Intersection of l1 and l2 is {5}
original list l1 is [1, 2, 3, 4, 5]
original list l2 is [9, 8, 7, 6, 5]
