create 4x4 array with random values , now create a new array from the said array such that it starts with the last row and goes till the first.

In [42]:
import numpy as np 

arr1 = np.arange(16)
arr1.shape
arr1


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [43]:
arr1 = arr1.reshape(4,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
new_array = arr1[::-1]


In [45]:
new_array

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])