get row numbers of numpy array if any element is having larger value than a specific value

In [7]:
import numpy as np

arr = np.array([[1,2,3,4],[2,5,7,9],[10,30,406,60],[13,5,63,67]])
np.vstack(arr)

array([[  1,   2,   3,   4],
       [  2,   5,   7,   9],
       [ 10,  30, 406,  60],
       [ 13,   5,  63,  67]])

In [11]:
given_element = 10

In [ ]:
np.where(np.any(arr > given_element,axis=0))  # axis 0 is column

(array([0, 1, 2, 3]),)

In [16]:
np.where(np.any(arr > given_element,axis=1))  # axis 1 is row


(array([2, 3]),)