In [20]:
import numpy as np 
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[9,8,7],[6,5,4],[3,2,1]])

In [22]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [21]:
arr1
arr2
np.ndim(arr1)
np.ndim(arr2)
arr1.shape
arr2.shape


(3, 3)

In [ ]:
np.multiply(arr1,arr2)  # this is wrong u want dot product

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [25]:
# np.dot(arr1,arr2) 
arr1.dot(arr2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [26]:
np.matmul(arr1,arr2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])